### ISSUE TITLE
Build fails due to problems accessing the docker image for postgres

### ISSUE THREAD

**Issue by ursjoss** [ursjoss/scipamato#260]
For a few days, all builds keep failing, e.g. https://github.com/ursjoss/scipamato/pull/259/checks?check_run_id=1852808211

<details><summary>Stacktrace</summary>
<pre>
Caused by: com.spotify.docker.client.exceptions.ImageNotFoundException: Image not found: postgres:10
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:747)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:724)
	at ch.ayedo.jooqmodelator.core.Modelator.generate(Modelator.kt:37)
	at ch.ayedo.jooqmodelator.gradle.JooqModelatorTask.generateMetamodel(JooqModelatorTask.kt:78)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	... 119 more
Caused by: com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/create: 404, body: {"message":"No such image: postgres:10"}

	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2840)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2723)
	at com.spotify.docker.client.DefaultDockerClient.createContainer(DefaultDockerClient.java:742)
	... 126 more
Caused by: javax.ws.rs.NotFoundException: HTTP 404 Not Found
	at org.glassfish.jersey.client.JerseyInvocation.convertToException(JerseyInvocation.java:1008)
	at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:816)
	at org.glassfish.jersey.client.JerseyInvocation.access$700(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$5.completed(JerseyInvocation.java:773)
	at org.glassfish.jersey.client.ClientRuntime.processResponse(ClientRuntime.java:198)
	at org.glassfish.jersey.client.ClientRuntime.access$300(ClientRuntime.java:79)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:180)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
</pre>
</details>

**Comment by ursjoss** [comment]
It looks like I need to log in with the docker registry, as anonymous access is now restricted

References:
- https://github.com/actions/virtual-environments/issues/1445
- https://www.docker.com/blog/what-you-need-to-know-about-upcoming-docker-hub-rate-limiting/
