### ISSUE TITLE
Searching for publication year ranges broken

### ISSUE THREAD

**Issue by ursjoss** [ursjoss/scipamato#84]
Searching for publication year like `>2016` is broken. Results in a NumberFormatException

```
Caused by: java.lang.NumberFormatException: For input string: ">"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:na]
        at java.base/java.lang.Integer.parseInt(Integer.java:652) ~[na:na]
        at java.base/java.lang.Integer.parseInt(Integer.java:770) ~[na:na]
        at ch.difty.scipamato.core.entity.search.IntegerSearchTerm.<init>(IntegerSearchTerm.java:108) ~[scipamato-core-entity-1.1.6.jar!/:1.1.6]
        at ch.difty.scipamato.core.entity.search.IntegerSearchTerm.<init>(IntegerSearchTerm.java:54) ~[scipamato-core-entity-1.1.6.jar!/:1.1.6]
        at ch.difty.scipamato.core.entity.search.IntegerSearchTerm.<init>(IntegerSearchTerm.java:50) ~[scipamato-core-entity-1.1.6.jar!/:1.1.6]
        at ch.difty.scipamato.core.entity.search.SearchTerm.newIntegerSearchTerm(SearchTerm.java:85) ~[scipamato-core-entity-1.1.6.jar!/:1.1.6]
        at ch.difty.scipamato.core.entity.search.SearchCondition.setIntegerValue(SearchCondition.java:475) ~[scipamato-core-entity-1.1.6.jar!/:1.1.6]
        at ch.difty.scipamato.core.entity.search.SearchCondition.setPublicationYear(SearchCondition.java:216) ~[scipamato-core-entity-1.1.6.jar!/:1.1.6]
        at jdk.internal.reflect.GeneratedMethodAccessor516.invoke(Unknown Source) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.apache.wicket.core.util.lang.PropertyResolver$MethodGetAndSet.setValue(PropertyResolver.java:999) ~[wicket-core-8.3.0.jar!/:8.3.0]
        ... 116 common frames omitted
```

**Comment by ursjoss** [comment]
Quick problem analysis:

The `PaperPanel` processes each character as it is typed. The `IntegerSearchTerm` thus first receives a `>` and cannot parse it, as it expects `>` with a total length of > 1 and falls into parsing the `>` as integer -> exception.

Two options I need to decide on:

* Enhance the `IntegerSearchTerm` to be able to deal with incomplete search term specification
* Disable the character by character processing for searches and only process complete search terms

The latter is definitely more efficient for the server and also more concise, as boiler-plate for dealing with an incomplete search term can be omitted. However, the user risks losing partially specified searches if she closes the browser or has a blue screen. Currently, the search is saved up to the point of the incident.

**Comment by ursjoss** [comment]
Workaround for now:

* Enter the year first `2017` (-> valid search term)
* Add the range operator as prefix in the end `>2017` (still valid search term)

**Comment by ursjoss** [comment]
I limited the scope of this ticket for `IntegerSearchTerms` to handle incomplete input. I'm currently not touching the character by character processing.

**Comment by ursjoss** [comment]
Also fixed searching by ID (`PSQLException: ERROR: column reference "id" is ambiguous`).
